version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  adminer:
    image: dpage/pgadmin4
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.ru
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"